/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-11-28 15:28:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class checkNickName_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("	<title>닉네임 중복 체크</title>\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"./css/custom.css\">\n");
      out.write("	<link rel=\"icon\" href=\"./img/favicon.png\">\n");
      out.write("	<style type=\"text/css\">\n");
      out.write("	</style>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		function pValue(){\n");
      out.write("			document.getElementById(\"NickName\").value = opener.document.userInfo.NickName.value;\n");
      out.write("		}\n");
      out.write("\n");
      out.write("		function sendCheckValue(){\n");
      out.write("			opener.document.userInfo.NickName.value = document.getElementById(\"NickName\").value;\n");
      out.write("			if (opener != null) {\n");
      out.write("            	opener.chkForm = null;\n");
      out.write("            	self.close();\n");
      out.write("			}	\n");
      out.write("		}	\n");
      out.write("	</script>\n");
      out.write("	\n");
      out.write("</head>\n");
      out.write("<body onload=\"pValue()\" class=\"text-center\" onsubmit=\"\">\n");
      out.write("<div id=\"wrap col-12\">\n");
      out.write("	<br>\n");
      out.write("	<h4>닉네임 중복체크</h4>\n");
      out.write("	<hr class=\"my-4\">\n");
      out.write("	<hr size=\"1\" width=\"460\">\n");
      out.write("	<br>\n");
      out.write("	<div id=\"chk\">\n");
      out.write("		<form method=\"post\" action=\"action/checkNickNameAction.jsp\" id=\"checkForm\">\n");
      out.write("			<div class=\"col-10 d-flex align-items-md-center container-xxl\">\n");
      out.write("				<input type=\"id\" class=\"form-control\" name=\"NickName\" id=\"NickName\" placeholder=\"\" style=\"margin-right: 10px\" required>\n");
      out.write("				<input class=\"col-3 btn\" style=\"background-color: #558DF0; color:white;\" type=\"submit\" value=\"중복확인\">\n");
      out.write("			</div>\n");
      out.write("		</form><br>\n");
      out.write("		<div class=\"gap-5 d-md-block align-items-md-center container-xxl\">\n");
      out.write("			<button class=\"col-3 btn float-right\" style=\"background-color: #558DF0; color:white;\" id=\"useID\" type=\"button\" onclick=\"sendCheckValue()\">사용하기</button>\n");
      out.write("			<button class=\"col-3 btn float-right\" style=\"background-color: #558DF0; color:white;\" id=\"cancel\" style=\"margin-left: 10%\" type=\"button\" onclick=\"window.close()\">취소</button>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("</div>	\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
