/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-11-28 15:28:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n");
      out.write("    <title>동퀴콩</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/custom.css\">\n");
      out.write("    <link rel=\"icon\" href=\"./image/favicon.png\">\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        function openCheckID(){\n");
      out.write("            window.name = \"parentForm\";\n");
      out.write("            window.open(\"checkID.jsp\",\n");
      out.write("                \"chkForm\", \"width=500, height=300, resizable = no, scrollbars = no\");\n");
      out.write("        }\n");
      out.write("        function openCheckNickName(){\n");
      out.write("            window.name = \"parentForm\";\n");
      out.write("            window.open(\"checkNickName.jsp\",\n");
      out.write("                \"chkForm\", \"width=500, height=300, resizable = no, scrollbars = no\");\n");
      out.write("        }\n");
      out.write("        function checkPassword(){\n");
      out.write("\n");
      out.write("            var password = document.getElementById('Password').value;\n");
      out.write("            var NB = [\"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\"]\n");
      out.write("            var SC = [\"!\",\"@\",\"#\",\"$\",\"%\"];\n");
      out.write("            var check_SC = 0, check_NB = 0;\n");
      out.write("\n");
      out.write("            if(password.length < 8 || password.length>20){\n");
      out.write("                window.alert('비밀번호는 8글자 이상, 20글자 이하만 이용 가능합니다.');\n");
      out.write("                document.getElementById('pw').value='';\n");
      out.write("            }\n");
      out.write("            for(var i=0;i<SC.length;i++){\n");
      out.write("                if(password.indexOf(SC[i]) != -1){\n");
      out.write("                    check_SC = 1;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            for(var i=0;i<NB.length;i++){\n");
      out.write("                if(password.indexOf(NB[i]) != -1){\n");
      out.write("                    check_NB = 1;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            if(check_SC == 0){\n");
      out.write("                window.alert('!,@,#,$,% 의 특수문자가 반드시 포함되어야 합니다.')\n");
      out.write("                document.getElementById('password').value='';\n");
      out.write("            }\n");
      out.write("            if(check_NB == 0){\n");
      out.write("                window.alert('숫자가 반드시 포함되어야 합니다.')\n");
      out.write("                document.getElementById('Password').value='';\n");
      out.write("            }\n");
      out.write("            if(document.getElementById('Password').value !='' && document.getElementById('PasswordVerify').value!=''){\n");
      out.write("                if(document.getElementById('Password').value==document.getElementById('PasswordVerify').value){\n");
      out.write("                    document.getElementById('check').innerHTML='비밀번호가 일치합니다.'\n");
      out.write("                    document.getElementById('check').style.color='blue';\n");
      out.write("                }\n");
      out.write("                else{\n");
      out.write("                    document.getElementById('check').innerHTML='비밀번호가 일치하지 않습니다.';\n");
      out.write("                    document.getElementById('check').style.color='red';\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        function checkValue() {\n");
      out.write("            if(document.userInfo.Password.value != document.userInfo.PasswordVerify.value) {\n");
      out.write("                alert(\"비밀번호가 일치하지 않습니다.\");\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("            else return true;\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light fixed-top shadow-sm\" style=\"background-color: #558DF0;\">\n");
      out.write("    <div class=\"container-xxl d-flex align-items-md-center\" style=\"width:1200px\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\"><img src=\"./img/mainIcon.png\" class=\"rounded float-start\" width=\"120\"></a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("            <ul class=\"navbar-nav me-auto\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"#\" style=\"font-size:15pt; color:white;\"><b>퀴즈 시작하기</b></a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"registerQuiz.jsp\" style=\"font-size:15pt; color:white;\"><b>퀴즈 만들기</b></a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("            ");

                String LoginID = null;
                String UserName = null;
                if(session.getAttribute("loginID") != null) {
                    LoginID = (String) session.getAttribute("LoginID");
                    UserName = (String) session.getAttribute("UserName");
                }
                if(LoginID == null) {
            
      out.write("\n");
      out.write("            <ul class=\"navbar-nav\">\n");
      out.write("                <a class=\"nav-link\" aria-current=\"page\" href=\"signUp.jsp\" style=\"color:white\">회원가입</a>\n");
      out.write("                <a class=\"btn btn-outline-primary\" href=\"login.jsp\" style=\"border-color: white; color: white\">로그인</a>\n");
      out.write("            </ul>\n");
      out.write("            ");

            } else {
            
      out.write("\n");
      out.write("            <ul class=\"navbar-nav d-flex\">\n");
      out.write("                <li class=\"nav-item dropdown\">\n");
      out.write("                    <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" style=\"color: white\">\n");
      out.write("                        ");
      out.print(UserName );
      out.write(" 님\n");
      out.write("                    </a>\n");
      out.write("                    <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\" style=\"background-color: #558DF0;\">\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"myPage.jsp\" style=\"color: white\">마이페이지</a></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\" style=\"color: white\">1:1 문의</a></li>\n");
      out.write("                        <li><hr class=\"dropdown-divider\" style=\"color: white\"></li>\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"logout.jsp\" style=\"color: white\">로그아웃</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("            ");

                }
            
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("<br><br><br><br>\n");
      out.write("<div class=\"py-5 text-center\">\n");
      out.write("    <h2><b>회원가입</b></h2>\n");
      out.write("</div>\n");
      out.write("<div class=\"container col-md-8 col-lg-6\">\n");
      out.write("    <hr class=\"my-4\">\n");
      out.write("    <h4 class=\"mb-3\"><b>기본 정보 입력</b></h4>\n");
      out.write("    <form method=\"post\" action=\"action/signUpAction.jsp\" name=\"userInfo\" onsubmit=\"return checkValue()\">\n");
      out.write("        <div class=\"row g-3\">\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <label for=\"UserName\" class=\"form-label\">이름</label>\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"UserName\" id=\"UserName\" placeholder=\"\" value=\"\" required>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <label for=\"LoginID\" class=\"form-label\">아이디<span class=\"text-muted\">(4자~12자리의 영문자 또는 영문자, 숫자 권장)</span></label>\n");
      out.write("                <div class=\"col-12 d-flex\">\n");
      out.write("                    <input type=\"id\" class=\"form-control\" name=\"LoginID\" id=\"LoginID\" placeholder=\"\" style=\"margin-right: 10px\" required>\n");
      out.write("                    <input type=\"button\" class=\"col-2 btn\" onclick=\"openCheckID()\" style=\"background-color: #558DF0; color:white; font-weight:bold\" value=\"중복확인\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <label for=\"Password\" class=\"form-label\">비밀번호<span class=\"text-muted\">(8자~20자리의 영문자, 숫자, 특수문자 반드시 포함)</span></label>\n");
      out.write("                <input type=\"password\" class=\"form-control\" name=\"Password\" id=\"Password\" placeholder=\"\" onchange=\"checkPassword()\" required>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <label for=\"passwordVerify\" class=\"form-label\">비밀번호 재입력</label>\n");
      out.write("                <input type=\"password\" class=\"form-control\" name=\"PasswordVerify\" id=\"PasswordVerify\" placeholder=\"\" onchange=\"checkPassword()\" required>\n");
      out.write("                &nbsp;<span id=\"check\"></span>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <label for=\"Email\" class=\"form-label\">이메일</label>\n");
      out.write("                <input type=\"email\" class=\"form-control\" name=\"Email\" id=\"Email\" placeholder=\"\" required>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12 d-flex\">\n");
      out.write("                <div class=\"col-4\">\n");
      out.write("                    <label for=\"Age\" class=\"form-label\">나이</label>\n");
      out.write("                    <select class=\"form-select\" name=\"Age\" id=\"Age\" required>\n");
      out.write("                        <option selected disabled hidden>선택</option>\n");
      out.write("                        <option>14</option>\n");
      out.write("                        <option>15</option>\n");
      out.write("                        <option>16</option>\n");
      out.write("                        <option>17</option>\n");
      out.write("                        <option>18</option>\n");
      out.write("                        <option>19</option>\n");
      out.write("                        <option>20</option>\n");
      out.write("                        <option>21</option>\n");
      out.write("                        <option>22</option>\n");
      out.write("                        <option>23</option>\n");
      out.write("                        <option>24</option>\n");
      out.write("                        <option>25</option>\n");
      out.write("                        <option>26</option>\n");
      out.write("                        <option>27</option>\n");
      out.write("                        <option>28</option>\n");
      out.write("                        <option>29</option>\n");
      out.write("                        <option>30</option>\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-7\">\n");
      out.write("                    <label for=\"Phone\" class=\"form-label\"style=\"margin-left:10%;\">전화번호</label>\n");
      out.write("                    <input type=\"number\" class=\"form-control\" name=\"Phone\" id=\"Phone\" placeholder=\"\" style=\"margin-left:10%; width:104.5%\" required>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <hr class=\"my-4\">\n");
      out.write("            <h4 class=\"mb-3\"><b>부가 정보 입력</b></h4>\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <label for=\"NickName\" class=\"form-label\">닉네임</label>\n");
      out.write("                <div class=\"col-12 d-flex\">\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"NickName\" id=\"NickName\" placeholder=\"\" style=\"margin-right: 10px\" required>\n");
      out.write("                    <button class=\"col-2 btn\" style=\"background-color: #558DF0; color:white;\" onclick=\"openCheckNickName()\"><b>중복확인</b></button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <label for=\"postCode\" class=\"form-label\">주소</label>\n");
      out.write("                <div class=\"col-12 d-flex\">\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"postCode\" id=\"postCode\" placeholder=\"우편번호\" style=\"margin-right: 10px\" required>\n");
      out.write("                    <button class=\"col-3 btn\" onclick=\"findPostalCode()\" style=\"background-color: #558DF0; color:white\"><b>우편번호 찾기</b></button>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"address\" id=\"address\" placeholder=\"주소\" required>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-12 d-flex\">\n");
      out.write("                <div class=\"col-7\">\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"detailAddress\" id=\"detailAddress\" placeholder=\"상세주소\" required>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-4\">\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"extraAddress\" id=\"extraAddress\" placeholder=\"참고항목\" style=\"margin-left:10%; width:115%\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"wrap\" style=\"display:none;border:5px solid #558DF0;width:500px;height:300px;position:relative;overflow-y:hidden\">\n");
      out.write("                <button type=\"button\" class=\"btn-close\" id=\"btnFoldWrap\" aria-label=\"Close\" style=\"cursor:pointer;position:absolute;right:0px;top:-1px;z-index:1\" onclick=\"foldPostcode()\"></button>\n");
      out.write("            </div>\n");
      out.write("            <script src=\"//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\n");
      out.write("            <script>\n");
      out.write("                var element_wrap = document.getElementById('wrap');\n");
      out.write("\n");
      out.write("                function foldPostcode() {\n");
      out.write("                    element_wrap.style.display = 'none';\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                function findPostalCode() {\n");
      out.write("                    var currentScroll = Math.max(document.body.scrollTop, document.documentElement.scrollTop);\n");
      out.write("                    new daum.Postcode({\n");
      out.write("                        oncomplete: function(data) {\n");
      out.write("                            var addr = '';\n");
      out.write("                            var extraAddr = '';\n");
      out.write("\n");
      out.write("                            if (data.userSelectedType === 'R') {\n");
      out.write("                                addr = data.roadAddress;\n");
      out.write("                            } else {\n");
      out.write("                                addr = data.jibunAddress;\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            if(data.userSelectedType === 'R'){\n");
      out.write("                                if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\n");
      out.write("                                    extraAddr += data.bname;\n");
      out.write("                                }\n");
      out.write("                                if(data.buildingName !== '' && data.apartment === 'Y'){\n");
      out.write("                                    extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\n");
      out.write("                                }\n");
      out.write("                                if(extraAddr !== ''){\n");
      out.write("                                    extraAddr = ' (' + extraAddr + ')';\n");
      out.write("                                }\n");
      out.write("                                document.getElementById(\"extraAddress\").value = extraAddr;\n");
      out.write("\n");
      out.write("                            } else {\n");
      out.write("                                document.getElementById(\"extraAddress\").value = '';\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                            document.getElementById('postCode').value = data.zonecode;\n");
      out.write("                            document.getElementById(\"address\").value = addr;\n");
      out.write("                            document.getElementById(\"detailAddress\").focus();\n");
      out.write("\n");
      out.write("                            element_wrap.style.display = 'none';\n");
      out.write("                            document.body.scrollTop = currentScroll;\n");
      out.write("                        },\n");
      out.write("                        onresize : function(size) {\n");
      out.write("                            element_wrap.style.height = size.height+'px';\n");
      out.write("                        },\n");
      out.write("                        width : '100%',\n");
      out.write("                        height : '110%'\n");
      out.write("                    }).embed(element_wrap);\n");
      out.write("                    element_wrap.style.display = 'block';\n");
      out.write("                }\n");
      out.write("            </script>\n");
      out.write("        </div><br><br>\n");
      out.write("        <button class=\"w-100 btn btn-lg btn\" type=\"submit\" style=\"background-color: #558DF0; color:white\"><b>회원가입</b></button><br>\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<footer class=\"bg-light mt-4 p-5 text-center\" style=\"color: #000000;\">\n");
      out.write("    2017112079 윤대현<br>2017112066 정호종<br>\n");
      out.write("    Copyright &copy; 2021 ddolI98 All Rights Reserved.\n");
      out.write("</footer>\n");
      out.write("<script src=\"./js/jquery.min.js\"></script>\n");
      out.write("<script src=\"./js/popper.js\"></script>\n");
      out.write("<script src=\"./js/bootstrap.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
