/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.72
 * Generated at: 2021-12-11 07:21:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import question.*;
import java.util.ArrayList;

public final class solveQuiz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("question");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	@SuppressWarnings("unchecked")
	ArrayList<QuestionDTO> qList = (ArrayList<QuestionDTO>)session.getAttribute("questionList");
	String type = String.valueOf(session.getAttribute("type"));
	int qnum = Integer.parseInt(String.valueOf(session.getAttribute("qnum")));
	session.setAttribute("qnum", qnum+1);
	int score = 0;
	if(qnum!=0) {
		score = Integer.parseInt(request.getParameter("score"));
	}
	session.setAttribute("score", score);
	
	QuestionDTO instance = qList.get(qnum);
	
	//qList.get(i).answer 이거 하면 답 번호 나옴

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html\"; charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <title>동퀴콘</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./css/custom.css\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./img/favicon.png\">\r\n");
      out.write("    <style>\r\n");
      out.write("	    .circle {\r\n");
      out.write("			position: fixed;\r\n");
      out.write("			transition-property: width, height, margin-left, margin-top;\r\n");
      out.write("			transition-duration: 0.5s;\r\n");
      out.write("			transform: translateX(-50%) translateY(-50%);\r\n");
      out.write("			border-radius: 50%;\r\n");
      out.write("			border: 50px solid #558DF0;\r\n");
      out.write("	    }\r\n");
      out.write("	    .digonal1 {\r\n");
      out.write("	    	position: fixed;\r\n");
      out.write("			background-color: #D65046;\r\n");
      out.write("			transform: rotate(-45deg);\r\n");
      out.write("		}\r\n");
      out.write("		.digonal2 {\r\n");
      out.write("	    	position: fixed;\r\n");
      out.write("			background-color: #D65046;\r\n");
      out.write("			transform: rotate(45deg);\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("	<script>\r\n");
      out.write("		function showCircle() {\r\n");
      out.write("			let div = document.createElement('div');\r\n");
      out.write("		    div.style.width = 0;\r\n");
      out.write("		    div.style.height = 0;\r\n");
      out.write("		    div.style.left = '50%';\r\n");
      out.write("		    div.style.top = '50%';\r\n");
      out.write("		    div.className = 'circle';\r\n");
      out.write("		    document.body.append(div);\r\n");
      out.write("\r\n");
      out.write("		    setTimeout(() => {\r\n");
      out.write("		      div.style.width = '400px';\r\n");
      out.write("		      div.style.height = '400px';\r\n");
      out.write("		    }, 0);\r\n");
      out.write("		}\r\n");
      out.write("		function showDiagonal() {\r\n");
      out.write("			let div1 = document.createElement('div1');\r\n");
      out.write("			div1.style.width = 0;\r\n");
      out.write("			div1.style.height = 0;\r\n");
      out.write("			div1.style.left = '49%';\r\n");
      out.write("			div1.style.top = '20%';\r\n");
      out.write("			div1.className = 'digonal1';\r\n");
      out.write("			document.body.append(div1);\r\n");
      out.write("			div1.style.width = '50px';\r\n");
      out.write("			div1.style.height = '400px';\r\n");
      out.write("			\r\n");
      out.write("			let div2 = document.createElement('div2');\r\n");
      out.write("			div2.style.width = 0;\r\n");
      out.write("			div2.style.height = 0;\r\n");
      out.write("			div2.style.left = '49%';\r\n");
      out.write("			div2.style.top = '20%';\r\n");
      out.write("			div2.className = 'digonal2';\r\n");
      out.write("			document.body.append(div2);\r\n");
      out.write("			div2.style.width = '50px';\r\n");
      out.write("			div2.style.height = '400px';\r\n");
      out.write("		}\r\n");
      out.write("		function compare(guess)  {\r\n");
      out.write("    		var answer=\"");
      out.print(String.valueOf(qList.get(qnum).answer));
      out.write("\";\r\n");
      out.write("    		var score=");
      out.print(Integer.parseInt(String.valueOf(session.getAttribute("score"))));
      out.write(";;\r\n");
      out.write("    		if(guess==answer) {\r\n");
      out.write("    			showCircle();\r\n");
      out.write("    			score = score + 1;\r\n");
      out.write("    		} else {\r\n");
      out.write("    			showDiagonal();\r\n");
      out.write("    		}\r\n");
      out.write("    		document.getElementById('score').value=score;\r\n");
      out.write("    	}\r\n");
      out.write("	</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light fixed-top shadow-sm\" style=\"background-color: #558DF0;\">\r\n");
      out.write("<div class=\"container-xxl d-flex align-items-md-center\" style=\"width:1200px\">\r\n");
      out.write("    <a class=\"navbar-brand\" href=\"index.jsp\"><img src=\"./img/mainIcon.png\" class=\"rounded float-start\" width=\"120\"></a>\r\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("        <ul class=\"navbar-nav me-auto\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"action/getQuestion.jsp?type=4\" style=\"font-size:15pt; color:white;\"><b>퀴즈 시작하기</b></a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"registerQuiz.jsp\" style=\"font-size:15pt; color:white;\"><b>퀴즈 만들기</b></a>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        ");

            String LoginID = null;
            String UserName = null;
            if(session.getAttribute("loginID") != null) {
                LoginID = (String) session.getAttribute("LoginID");
                UserName = (String) session.getAttribute("UserName");
            }
            if(LoginID == null) {
        
      out.write("\r\n");
      out.write("        <ul class=\"navbar-nav\">\r\n");
      out.write("            <a class=\"nav-link\" aria-current=\"page\" href=\"signUp.jsp\" style=\"color:white\">회원가입</a>\r\n");
      out.write("            <a class=\"btn btn-outline-primary\" href=\"login.jsp\" style=\"border-color: white; color: white\">로그인</a>\r\n");
      out.write("        </ul>\r\n");
      out.write("        ");

        } else {
        
      out.write("\r\n");
      out.write("        <ul class=\"navbar-nav d-flex\">\r\n");
      out.write("            <li class=\"nav-item dropdown\">\r\n");
      out.write("                <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\" style=\"color: white\">\r\n");
      out.write("                    ");
      out.print(UserName );
      out.write(" 님\r\n");
      out.write("                </a>\r\n");
      out.write("                <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\" style=\"background-color: #558DF0;\">\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"myPage.jsp\" style=\"color: white\">마이페이지</a></li>\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\" style=\"color: white\">1:1 문의</a></li>\r\n");
      out.write("                    <li><hr class=\"dropdown-divider\" style=\"color: white\"></li>\r\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"logout.jsp\" style=\"color: white\">로그아웃</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</nav><br><br><br><br><br>\r\n");
      out.write("	<script type=\"text/javascript\" src=\"./js/main.js?ver=123\">\r\n");
      out.write("		alert(guess.equals(");
      out.print(qList.get(qnum).answer );
      out.write(");\r\n");
      out.write("    </script>\r\n");
      out.write("<div class=\"py-5 text-center\">\r\n");
      out.write("    <h2><b>");
      out.print( type );
      out.write("</b></h2>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container col-md-4\">\r\n");
      out.write("	");

		if (qList.get(qnum).type) {
			
	
      out.write("\r\n");
      out.write("		<div class=\"col-12\" style=\"height:150px; text-align:center; font-size:25px; font-weight:bold; border-radius:5px\">\r\n");
      out.write("			<img src = \"");
      out.print(qList.get(qnum).questionContent);
      out.write("\" style = \"width: 250px; height:150px; border:3px solid black;\">\r\n");
      out.write("		</div>\r\n");
      out.write("	");

		} else {
	
      out.write("\r\n");
      out.write("		<div class=\"col-12\" style=\"height:150px; padding:50px; background-color: #EAEAEA; text-align:center; font-size:25px; font-weight:bold; border-radius:5px\">\r\n");
      out.write("			 <label class=\"form-label\">Q : ");
      out.print(qList.get(qnum).questionContent );
      out.write("</label>\r\n");
      out.write("		</div>		\r\n");
      out.write("    ");

		}
    
      out.write("\r\n");
      out.write("		<br><br><br><br>\r\n");
      out.write("	");

		if (qnum < 9) {	
	
      out.write("\r\n");
      out.write("	<form method=\"post\" action=\"solveQuiz.jsp\">\r\n");
      out.write("	");

		} else {
	
      out.write("\r\n");
      out.write("	<form method=\"post\" action=\"resultQuiz.jsp\">\r\n");
      out.write("	");

		}
	
      out.write("\r\n");
      out.write("        <div class=\"row g-3\">\r\n");
      out.write("        	<button class=\"w-100 btn-lg\" style=\"background-color: white; color:#558DF0; border:3px solid #558DF0\" name = \"answer\" value = \"1\" onclick=\"compare(this.value)\"><b>1. ");
      out.print(qList.get(qnum).example1 );
      out.write("</b></button>\r\n");
      out.write("            <button class=\"w-100 btn-lg\" style=\"background-color: white; color:#558DF0; border:3px solid #558DF0\" name = \"answer\" value = \"2\" onclick=\"compare(this.value)\"><b>2. ");
      out.print(qList.get(qnum).example2 );
      out.write("</b></button>\r\n");
      out.write("            <button class=\"w-100 btn-lg\" style=\"background-color: white; color:#558DF0; border:3px solid #558DF0\" name = \"answer\" value = \"3\" onclick=\"compare(this.value)\"><b>3. ");
      out.print(qList.get(qnum).example3 );
      out.write("</b></button>\r\n");
      out.write("            <button class=\"w-100 btn-lg\" style=\"background-color: white; color:#558DF0; border:3px solid #558DF0\" name = \"answer\" value = \"4\" onclick=\"compare(this.value)\"><b>4. ");
      out.print(qList.get(qnum).example4 );
      out.write("</b></button>\r\n");
      out.write("            <input type=\"hidden\" id=\"score\" name=\"score\">\r\n");
      out.write("    ");

    		Thread.sleep(1500);
    
      out.write("\r\n");
      out.write("        </div><br><br>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<footer class=\"bg-light mt-4 p-5 text-center\" style=\"color: #000000;\">\r\n");
      out.write("    2017112079 윤대현<br>2017112066 정호종<br>\r\n");
      out.write("    Copyright &copy; 2021 ddolI98 All Rights Reserved.\r\n");
      out.write("</footer>\r\n");
      out.write("<script src=\"./js/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"./js/popper.js\"></script>\r\n");
      out.write("<script src=\"./js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
